export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const LOAD_BOOKS_SUCCESS = "LOAD_BOOKS_SUCCESS";
export const SEARCH_BOOKS_SUCCESS = "SEARCH_BOOKS_SUCCESS";
export const LOADING_BOOKS_SUCCESS = "LOADING_BOOKS_SUCCESS";
export const ERROR_BOOKS = "ERROR_BOOKS";

